# Use Nginx lightweight image
FROM nginx:alpine

# Set working directory
WORKDIR /usr/share/nginx/html

# Copy all HTML files into Nginx web root
COPY index.html .
COPY login-hash.html .
COPY login-auth.html .
COPY pay.html .

# Expose port 80
EXPOSE 80

# Run Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
